# Generated by Django 5.0.6 on 2024-06-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='course',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='title',
            new_name='topic',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
