# Generated by Django 5.0.6 on 2024-06-06 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_lecture_course_rename_title_lecture_topic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsdb',
            name='section',
        ),
        migrations.RemoveField(
            model_name='studentsdb',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='studentsdb',
            name='year',
        ),
    ]
