# Generated by Django 5.0.6 on 2024-06-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_studentsdb_section_remove_studentsdb_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attended',
            field=models.BooleanField(default=True),
        ),
    ]
