# Generated by Django 4.0.5 on 2024-06-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_attendance_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsdb',
            name='profile_img',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
