# Generated by Django 4.0.5 on 2024-06-09 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_studentsdb_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=10)),
                ('email', models.CharField(max_length=500)),
                ('login_time', models.DateTimeField(default=datetime.datetime.now)),
                ('msg', models.TextField()),
            ],
        ),
    ]
